pipeline {
    agent none

    stages {
        stage('UI Tests') {
            agent {
                docker {
                    image 'automation'
                    reuseNode true
                }
            }
            steps {
                dir('tests') {
                    sh 'robot --version'
                    sh 'ls'
                    sh 'robot -d results .'

                }
            }

        }
    }
}