pipeline {
    agent any

    stages {
        stage('UI Tests') {
            agent {
                image 'automation'
                reuseNode true
            }
            steps {
                dir('tests') {
                    sh 'robot --version'
                    sh 'ls'
                    sh 'robot -d results .'

                }
            }

        }
    }
}