pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile' 
            dir '.'                 
            additionalBuildArgs '--pull'
        }
    }

    stages {
        stage('UI Tests') {
            steps {

                sh 'python --version || echo "Ei pythonia"'
                sh 'robot --version || echo "Robot ei löydy"'
                sh 'pwd'
                sh 'ls -R'


                sh 'cd tests && ls'
                sh 'cd tests && robot -d results .'
            }
        }
    }
}